version: '3'

services:
  postgresql:
      image: postgres:11.5
      container_name: msg_bdd
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: msg
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: test
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
      container_name: pgadmin_msg
      image: dpage/pgadmin4
      depends_on:
          - postgresql
      ports:
          - "5555:80"
      environment:
          PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
          PGADMIN_DEFAULT_PASSWORD: admin
      restart: unless-stopped
